### ISSUE TITLE
Build error with GHC 8.8.1

### ISSUE THREAD

**Issue by asr** [ChrisKuklewicz/regex-tdfa#23]
GHC 8.8.1-alpha2 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2019-June/017777.html).

Using this version of GHC, I got the error

```bash
$ cabal install
Building library for regex-base-0.93.1..
[1 of 4] Compiling Text.Regex.Base.RegexLike ( Text/Regex/Base/RegexLike.hs, dist/build/Text/Regex/Base/RegexLike.o )
[2 of 4] Compiling Text.Regex.Base.Context ( Text/Regex/Base/Context.hs, dist/build/Text/Regex/Base/Context.o )

Text/Regex/Base/Context.hs:267:16: error:
    • Could not deduce (MonadFail m) arising from a use of ‘fail’
      from the context: Monad m
        bound by the type signature for:
                   regexFailed :: forall (m :: * -> *) b. Monad m => m b
        at Text/Regex/Base/Context.hs:265:1-31
      Possible fix:
        add (MonadFail m) to the context of
          the type signature for:
            regexFailed :: forall (m :: * -> *) b. Monad m => m b
    • In the expression: fail $ "regex failed to match"
      In an equation for ‘regexFailed’:
          regexFailed = fail $ "regex failed to match"
    |
267 | regexFailed =  fail $ "regex failed to match"
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Question: After fixing the errors in my local repository of `regex-base`,  I got a couple of errors in `regex-tdfa` which I have also fixed. Before creating a PR fixing the problems with `regex-tdfa` I need to create a PR fixing the problems with `regex-base`. Where should I create the PR for `regex-base`? 

Blocking https://github.com/agda/agda/issues/3725.

**Comment by neongreen** [comment]
Pinging @ChrisKuklewicz. I don't have access to regex-base.

**Comment by asr** [comment]
Any news?

**Comment by RyanGlScott** [comment]
Aside from `regex-base` and `regex-tdfa`, the following libraries in the `regex-*` diaspora also fail to build with GHC 8.8.1:

* `regex-pcre`:

  <details>

  ```
  Building library for regex-pcre-0.94.4..
  [1 of 6] Compiling Text.Regex.PCRE.Wrap ( /home/rgscott/Documents/Hacking/Haskell/staging/dist-newstyle/build/x86_64-linux/ghc-8.8.1/regex-pcre-0.94.4/build/Text/Regex/PCRE/Wrap.hs, /home/rgscott/Documents/Hacking/Haskell/staging/dist-newstyle/build/x86_64-linux/ghc-8.8.1/regex-pcre-0.94.4/build/Text/Regex/PCRE/Wrap.o )

  Text/Regex/PCRE/Wrap.hsc:164:33: error:
      • Could not deduce (MonadFail m) arising from a use of ‘makeRegexM’
        from the context: (RegexMaker Regex CompOption ExecOption source,
                           RegexContext Regex source1 target, Monad m)
          bound by the type signature for:
                     (=~~) :: forall source source1 target (m :: * -> *).
                              (RegexMaker Regex CompOption ExecOption source,
                               RegexContext Regex source1 target, Monad m) =>
                              source1 -> source -> m target
          at Text/Regex/PCRE/Wrap.hsc:(143,1)-(144,38)
        Possible fix:
          add (MonadFail m) to the context of
            the type signature for:
              (=~~) :: forall source source1 target (m :: * -> *).
                       (RegexMaker Regex CompOption ExecOption source,
                        RegexContext Regex source1 target, Monad m) =>
                       source1 -> source -> m target
      • In a stmt of a 'do' block: (q :: Regex) <- makeRegexM r
        In the expression:
          do (q :: Regex) <- makeRegexM r
             matchM q x
        In an equation for ‘=~~’:
            (=~~) x r
              = do (q :: Regex) <- makeRegexM r
                   matchM q x
      |
  164 | (=~~) x r = do (q :: Regex) <-  makeRegexM r
      |                                 ^^^^^^^^^^^^
  ```
  </details>
* `regex-posix`:

  <details>

  ```
  Building library for regex-posix-0.95.2..
  [1 of 6] Compiling Text.Regex.Posix.Wrap ( /home/rgscott/Documents/Hacking/Haskell/staging/dist-newstyle/build/x86_64-linux/ghc-8.8.1/regex-posix-0.95.2/build/Text/Regex/Posix/Wrap.hs, /home/rgscott/Documents/Hacking/Haskell/staging/dist-newstyle/build/x86_64-linux/ghc-8.8.1/regex-posix-0.95.2/build/Text/Regex/Posix/Wrap.o )

  Text/Regex/Posix/Wrap.hsc:341:16: error:
      • Could not deduce (MonadFail m) arising from a use of ‘matchM’
        from the context: (RegexMaker Regex CompOption ExecOption source,
                           RegexContext Regex source1 target, Monad m)
          bound by the type signature for:
                     (=~~) :: forall source source1 target (m :: * -> *).
                              (RegexMaker Regex CompOption ExecOption source,
                               RegexContext Regex source1 target, Monad m) =>
                              source1 -> source -> m target
          at Text/Regex/Posix/Wrap.hsc:(322,1)-(323,38)
        Possible fix:
          add (MonadFail m) to the context of
            the type signature for:
              (=~~) :: forall source source1 target (m :: * -> *).
                       (RegexMaker Regex CompOption ExecOption source,
                        RegexContext Regex source1 target, Monad m) =>
                       source1 -> source -> m target
      • In the expression: matchM (make r) x
        In the expression:
          let
            make :: RegexMaker Regex CompOption ExecOption a => a -> Regex
            make = makeRegex
          in matchM (make r) x
        In an equation for ‘=~~’:
            (=~~) x r
              = let
                  make :: RegexMaker Regex CompOption ExecOption a => a -> Regex
                  make = makeRegex
                in matchM (make r) x
      |
  341 |             in matchM (make r) x
      |                ^^^^^^^^^^^^^^^^^
  ```
  </details>

Unfortunately, neither of these libraries have issue trackers AFAICT.

**Comment by asr** [comment]
In relation to `regex-base` see https://github.com/haskell-infra/hackage-trustees/issues/238.

**Comment by peti** [comment]
Will you release a new version that contains these fixes?

**Comment by neongreen** [comment]
regex-tdfa already builds fine on GHC 8.8.1, see https://matrix.hackage.haskell.org/#/package/regex-tdfa.

**Comment by peti** [comment]
Oh, you are right! I somehow missed the `regex-tdfa-1.3.0` release. Thank you for the quick response.
